artifacts : artifacts

data_ingestion :
  root_dir : artifacts/data_ingestion
  source_url : https://raw.githubusercontent.com/Ahmed/End_to_End_Machine_Learning_Project/main/data/students_performance.csv
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion

data_validation :
  root_dir : artifacts/data_validation
  unzip_dir : artifacts/data_ingestion/data.csv
  status_file : artifacts/data_validation/status.txt